[general]
live_config_reload = true

[font]
size = 8.0

[font.bold]
family = "monospace"

[font.italic]
family = "monospace"

[font.normal]
family = "monospace"

[window]
decorations = "none"
dynamic_padding = false
opacity = 1.0
startup_mode = "Maximized"

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0xeaeaea"
yellow = "0xe6c547"

# [[keyboard.bindings]]
# chars = ""
# key = "T"
# mods = "Control"

# [[keyboard.bindings]]
# chars = "\u001B[1;6D"
# key = "Left"
# mods = "Control|Shift"

# [[keyboard.bindings]]
# chars = "\u001B[1;6D"
# key = "Left"
# mods = "Control|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B[1;6C"
# key = "Right"
# mods = "Control|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B[1;6A"
# key = "Up"
# mods = "Control|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B[1;6B"
# key = "Down"
# mods = "Control|Shift"
