#!/usr/bin/env python
# -*- coding: utf-8 -*-

##=Raw================
# hex:    0xDEADBEEF
# to hex: hex(number)

# binary: 0b1011_1111
# to bin: bin(number)

# octet:  0100

# char -> raw: ord('a')
# raw -> char: chr(97)

# Math functions
# math.log(x)
# xor(x,y)

# hex encoded -> utf8 string
# bytearray.fromhex(hex).decode('utf-8')
# hex encoded -> raw
# binascii.unhexlify(hex)

# sha256
# m = hashlib.sha256()
# m.update(binascii.unhexlify(""))
# m.hexdigest()

# random
# hex(random.getrandbits(32))
# ===================

import sys
import math
import binascii
import hashlib
import random
from operator import xor

sys.setrecursionlimit(1500)

